openapi: 3.0.0
info:
  title: My Flask App
  version: 1.0.0
paths:
  /success:
    get:
      summary: Endpoint for success
      responses:
        '200':
          description: A successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Success
  /failure:
    get:
      summary: Endpoint for failure
      responses:
        '500':
          description: A failure response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Failure
